### ISSUE TITLE
BUG - hash ignores empty list fields in dictionary

### ISSUE THREAD

**Issue by NiroHaim** [cobaltine/json-fingerprint#33]
Hi!
First off, thank you for the awesome lib! Really helped me out when I couldn't finding anything else that could really hash a JSON properly.

I've encountered a bug in the usage of the lib
When running the code snippet below, The received output is True which clearly shouldn't be the case.
```python
import json
import json_fingerprint

hash1 = json_fingerprint.create(
    input=json.dumps({'field1': 'yes'}),
    hash_function='sha256',
    version=1
)

hash2 = json_fingerprint.create(
    input=json.dumps({'field1': 'yes', 'field2': []}),
    hash_function='sha256',
    version=1
)

print(hash1 == hash2)  # True
```

After a short debug session, I found that the problem lies in the recursive `_flatten_json` function. This unexpected behavior happens because the function loops the elements of a dict/list recursivley and hashes its inner elements.
When the dict/list is empty, an empty list is returned and in the logic, the out result is extended which does nothing when handling an empty list.
This means that fields of empty dicts or lists in the desired hashing object are being ignored.
I'd be happy to provide more insight if needed to further a solution to the bug :)

Thanks!

**Comment by cobaltine** [comment]
Thank you @NiroHaim for reporting the issue and providing a thorough explanation -- as well as the code snippet!

I'll soon* have a look at the issue in more detail, build a unit test for it, and deploy a fix. This project has been dormant for quite some time so fixing this issue means some long overdue refactoring of the ci/cd pipeline just needs to be done prior to that.
